spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jiujitsu_system
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
  jackson:
    property-naming-strategy: SNAKE_CASE

  output:
    ansi:
      enabled: ALWAYS